# Generated by Django 5.0 on 2024-01-05 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='image_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
