# Generated by Django 5.0.1 on 2024-01-08 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0006_cartitem_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='long_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
